apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails-app.fullname" . }}
  labels:
    app: {{ include "rails-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "rails-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rails-app.name" . }}
    spec:
      containers:
        - name: rails
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10

