apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-app
  labels:
    app: rails-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rails-app
  template:
    metadata:
      labels:
        app: rails-app
    spec:
      containers:
        - name: rails
          image: maxkerim/rails-app:latest
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: RAILS_ENV
              value: production

