apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.43.3
    chart: grafana
    helm:
      values: |
        adminUser: admin
        adminPassword: admin
        service:
          type: NodePort
          port: 3000
        datasources:
          datasources:
            - name: VictoriaMetrics
              type: prometheus
              access: proxy
              url: http://victoriametrics-victoria-metrics-single-server.monitoring.svc.cluster.local:8428
              isDefault: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

