apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victorialogs
  namespace: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/VictoriaMetrics/helm-charts
    chart: victorialogs
    targetRevision: 0.4.2
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
