adminUser: admin
adminPassword: admin

service:
  type: NodePort
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics-victoria-metrics-single-server.monitoring.svc.cluster.local:8428
        isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    node-exporter-full:
      gnetId: 1860
      revision: 33
      datasource: VictoriaMetrics

