adminUser: admin
adminPassword: admin

service:
  type: NodePort
  port: 3000

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics-victoria-metrics-single-server.monitoring.svc.cluster.local:8428
        isDefault: true

