apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.scrapeInterval }}
    scrape_configs:
{{ toYaml .Values.scrape_configs | indent 6 }}

