apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vmagent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vmagent
    spec:
      containers:
        - name: vmagent
          image: victoriametrics/vmagent:v1.93.0
          args:
            - "-remoteWrite.url={{ .Values.remoteWrite.url }}"
            - "-promscrape.config=/etc/prometheus/prometheus.yml"
            - "-httpListenAddr=:8428"
          ports:
            - name: http
              containerPort: 8428
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: vmagent-config

