apiVersion: v1
kind: Service
metadata:
  name: vmagent
  namespace: monitoring
  labels:
    app.kubernetes.io/name: vmagent
spec:
  selector:
    app.kubernetes.io/name: vmagent
  ports:
    - protocol: TCP
      port: 8428
      targetPort: 8428

