apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Oshtuk/monitoring-gitops
    targetRevision: HEAD
    path: charts/nginx-app
  destination:
    server: https://kubernetes.default.svc
    namespace: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
